[package]
name = "orbgame"
version = "0.1.0"
description = "The Orbital 2D Game engine"
authors = ["Florian Blasius <flovanpt at posteo.de>"]
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "game",
    "2D",
    "engine",
    "tiles"
]

[lib]
name = "orbgame"
path = "src/lib.rs"

[profile.dev]
opt-level = 1

[dependencies]
orbclient = "0.3.13"
orbtk = { git = "https://github.com/redox-os/orbtk.git" }
orbimage = "0.1.15"
serde = "1.0"
serde_derive = "1.0"
chrono = "0.4"
fps_counter = "1.0.0"
rhai = "0.8.1"
ron = "0.1.5"
regex = "0.2"

[patch.crates-io]
orbclient = { git = "https://github.com/robbycerantola/orbclient.git" }
